from __future__ import annotations

STABLE_API_SYMBOLS: tuple[str, ...] = (
    "__version__",
    "GovernanceLayer",
    "GuardedMemoryBackend",
    "AdmissionPolicy",
    "AppendOnlyLedger",
    "LedgerVerificationResult",
    "RetrievalFilterResult",
    "ContaminationLane",
    "MemoryEvent",
    "MemoryCandidate",
    "MemoryStatus",
    "MemoryEventType",
    "AdmissionDecision",
    "BackendName",
    "ProtectedAction",
    "AuthorityBundle",
    "AuthorityEvidenceBundle",
    "AuthorityReceipt",
    "DeclaredScope",
    "ProtectedActionRequest",
    "GovernanceReceiptBundle",
    "PromotionReceipt",
    "RetrievalDecision",
    "authorize_bundle",
    "authorize_request",
    "make_declared_scope",
    "make_protected_action_request",
    "filter_retrieval",
    "sha256_digest",
)
